// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrustructure.Migrations
{
    [DbContext(typeof(RTSDbContext))]
    [Migration("20240331134953_RTSModel")]
    partial class RTSModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.DependentCreditNote", b =>
                {
                    b.Property<long>("CreditNumber")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.Property<int>("CreditStatus")
                        .HasColumnType("int");

                    b.Property<string>("ExternalCreditNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("InvoiceDocumentInvoiceNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentInvoiceNumber")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CreditNumber");

                    b.HasIndex("CreditNumber")
                        .IsUnique()
                        .HasDatabaseName("RTSCreditNumber_IDX01");

                    b.HasIndex("InvoiceDocumentInvoiceNumber");

                    b.ToTable("RTS_DependentCreditNote", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InDependentCreditNote", b =>
                {
                    b.Property<long>("CreditNumber")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.Property<int>("CreditStatus")
                        .HasColumnType("int");

                    b.Property<string>("ExternalCreditNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CreditNumber");

                    b.HasIndex("CreditNumber")
                        .IsUnique()
                        .HasDatabaseName("RTS_InDependentCreditNote_IDX01");

                    b.ToTable("RTS_InDependentCreditNote", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InvoiceDocument", b =>
                {
                    b.Property<long>("InvoiceNumber")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("InvoiceStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceNumber");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("RTS_InvoiceDocument_IDX1");

                    b.ToTable("RTS_InvoiceDocument", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DependentCreditNote", b =>
                {
                    b.HasOne("Domain.Entities.InvoiceDocument", "InvoiceDocument")
                        .WithMany("DependentCreditNote")
                        .HasForeignKey("InvoiceDocumentInvoiceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceDocument");
                });

            modelBuilder.Entity("Domain.Entities.InvoiceDocument", b =>
                {
                    b.Navigation("DependentCreditNote");
                });
#pragma warning restore 612, 618
        }
    }
}
